server:
  port: 9300
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: admin
    password: 1234!12
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    web:
      debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
