server:
  port: 9000
  name: auth-dev

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cheese-dev-instance-1.crnql90rczbs.ap-northeast-2.rds.amazonaws.com:3306/cheese?useSSL=false
    username: admin
    password: amlabs!25
    hikari:
      maximum-pool-size: 5
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
  user:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  partner:
    secret: ED7d26oSnUy4mTUPHrWNnUL1JkZ0aWPG5g0NYZI38mY7U3qbarcD4Ga7HVmGyAeRIYmD2y3WG812i6FEUc4oPeJ9PM0Vh5bHYw6o

naver:
  sms:
    from: 01092069357
    serviceId: ncp:sms:kr:283083821753:cheese_test
    client: dZjHvYUqnbSlBMbeWicw
    secret: QHmiPMddHiNomgx6iAK160hTR3b53PblLDmapU9A
    url: https://sens.apigw.ntruss.com

danal:
  cpid: B010007507
  cppwd: YJZGsoLmhb
  auth:
    url: https://uas.teledit.com
  ready:
    url: https://wauth.teledit.com/Danal/WebAuth/Mobile/Start.php
  cpcgi:
    url: https://auth.cheesepoint.kr/auth/danal/callback
  back:
    url: https://auth.cheesepoint.kr/auth/danal/back

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    web:
      debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace