
version: "3" 
services: 
  db: 
    platform: linux/x86_64
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123!@#"
      MYSQL_DATABASE: "test"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
   # volumes:
   #   - /home/ec2-user/db:/var/lib/mysql
