server:
  port: 9200
  name: test-api
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2.com:3306/test?useSSL=false
    username: root
    password: qwe123!@#
    hikari:
      maximum-pool-size: 5
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
es:
  host: https://search-test-adsadsaad.ap-northeast-2.es.amazonaws.com:443
  username: admin
  password: Dnflskfk!23