server:
  port: 9200
  name: test-api

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheese
    username: root
    password: dnflskfk!23
    hikari:
      maximum-pool-size: 2
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
es:
  host: https://search-cheesepointkr-niivuevkfc3y7mle36dem37jfm.ap-northeast-2.es.amazonaws.com:443
  username: admin
  password: Dnflskfk!23